### ISSUE TITLE
Font name is incorrect

### ISSUE THREAD

**Issue by fee1good** [aforizm/avatar-change-time#1]
`font = ImageFont.truetype("arial.ttf", FONT_SIZE)`

Привет! Отличная реализация, один момент правда — у меня на маке не подтянулся шрифт, должен, вроде как, передаваться `Arial.ttf`.

**Comment by aforizm** [comment]
Привет, шрифт нужно обязательно кинуть в корневой каталог, причем регистр букв должен быть одинаков, что в названии файла шрифта, что в ("arial.ttf", FONT_SIZE)
